#!/bin/bash 

rm -rf "run.dpp-local-nc8_gl5-1.warmup.cfg"

job0_0=$(sbatch --job-name="info.before.dpp-local-nc8_gl5-1.warmup.cfg" -w gl5 -n 1 collect-info.before.sh | awk '{print $NF}')
job0_1=$(sbatch --job-name="dpp-local-nc8_gl5-1.warmup.cfg" -w gl5 -n 8 --dependency=afterany:$job0_0 haddock3 "dpp-local-nc8_gl5-1.warmup.cfg" | awk '{print $NF}')
job0_2=$(sbatch --job-name="info.after.dpp-local-nc8_gl5-1.warmup.cfg" -w gl5 -n 1 --dependency=afterany:$job0_1 collect-info.after.sh | awk '{print $NF}')
job1_0=$(sbatch --job-name="info.before.daa-local-nc32_gl5-11.cfg" -w gl5 -n 1 --dependency=afterany:$job0_2 collect-info.before.sh | awk '{print $NF}')
job1_1=$(sbatch --job-name="daa-local-nc32_gl5-11.cfg" -w gl5 -n 32 --dependency=afterany:$job1_0 haddock3 "daa-local-nc32_gl5-11.cfg" | awk '{print $NF}')
job1_2=$(sbatch --job-name="info.after.daa-local-nc32_gl5-11.cfg" -w gl5 -n 1 --dependency=afterany:$job1_1 collect-info.after.sh | awk '{print $NF}')
job2_0=$(sbatch --job-name="info.before.daa-local-nc2_gl5-12.cfg" -w gl5 -n 1 --dependency=afterany:$job1_2 collect-info.before.sh | awk '{print $NF}')
job2_1=$(sbatch --job-name="daa-local-nc2_gl5-12.cfg" -w gl5 -n 2 --dependency=afterany:$job2_0 haddock3 "daa-local-nc2_gl5-12.cfg" | awk '{print $NF}')
job2_2=$(sbatch --job-name="info.after.daa-local-nc2_gl5-12.cfg" -w gl5 -n 1 --dependency=afterany:$job2_1 collect-info.after.sh | awk '{print $NF}')
job3_0=$(sbatch --job-name="info.before.dpp-local-nc2_gl5-15.cfg" -w gl5 -n 1 --dependency=afterany:$job2_2 collect-info.before.sh | awk '{print $NF}')
job3_1=$(sbatch --job-name="dpp-local-nc2_gl5-15.cfg" -w gl5 -n 2 --dependency=afterany:$job3_0 haddock3 "dpp-local-nc2_gl5-15.cfg" | awk '{print $NF}')
job3_2=$(sbatch --job-name="info.after.dpp-local-nc2_gl5-15.cfg" -w gl5 -n 1 --dependency=afterany:$job3_1 collect-info.after.sh | awk '{print $NF}')
job4_0=$(sbatch --job-name="info.before.dpp-local-nc8_gl5-13.cfg" -w gl5 -n 1 --dependency=afterany:$job3_2 collect-info.before.sh | awk '{print $NF}')
job4_1=$(sbatch --job-name="dpp-local-nc8_gl5-13.cfg" -w gl5 -n 8 --dependency=afterany:$job4_0 haddock3 "dpp-local-nc8_gl5-13.cfg" | awk '{print $NF}')
job4_2=$(sbatch --job-name="info.after.dpp-local-nc8_gl5-13.cfg" -w gl5 -n 1 --dependency=afterany:$job4_1 collect-info.after.sh | awk '{print $NF}')
job5_0=$(sbatch --job-name="info.before.daa-local-nc4_gl5-12.cfg" -w gl5 -n 1 --dependency=afterany:$job4_2 collect-info.before.sh | awk '{print $NF}')
job5_1=$(sbatch --job-name="daa-local-nc4_gl5-12.cfg" -w gl5 -n 4 --dependency=afterany:$job5_0 haddock3 "daa-local-nc4_gl5-12.cfg" | awk '{print $NF}')
job5_2=$(sbatch --job-name="info.after.daa-local-nc4_gl5-12.cfg" -w gl5 -n 1 --dependency=afterany:$job5_1 collect-info.after.sh | awk '{print $NF}')
job6_0=$(sbatch --job-name="info.before.daa-local-nc2_gl5-14.cfg" -w gl5 -n 1 --dependency=afterany:$job5_2 collect-info.before.sh | awk '{print $NF}')
job6_1=$(sbatch --job-name="daa-local-nc2_gl5-14.cfg" -w gl5 -n 2 --dependency=afterany:$job6_0 haddock3 "daa-local-nc2_gl5-14.cfg" | awk '{print $NF}')
job6_2=$(sbatch --job-name="info.after.daa-local-nc2_gl5-14.cfg" -w gl5 -n 1 --dependency=afterany:$job6_1 collect-info.after.sh | awk '{print $NF}')
job7_0=$(sbatch --job-name="info.before.daa-local-nc2_gl5-17.cfg" -w gl5 -n 1 --dependency=afterany:$job6_2 collect-info.before.sh | awk '{print $NF}')
job7_1=$(sbatch --job-name="daa-local-nc2_gl5-17.cfg" -w gl5 -n 2 --dependency=afterany:$job7_0 haddock3 "daa-local-nc2_gl5-17.cfg" | awk '{print $NF}')
job7_2=$(sbatch --job-name="info.after.daa-local-nc2_gl5-17.cfg" -w gl5 -n 1 --dependency=afterany:$job7_1 collect-info.after.sh | awk '{print $NF}')
job8_0=$(sbatch --job-name="info.before.dpp-local-nc32_gl5-12.cfg" -w gl5 -n 1 --dependency=afterany:$job7_2 collect-info.before.sh | awk '{print $NF}')
job8_1=$(sbatch --job-name="dpp-local-nc32_gl5-12.cfg" -w gl5 -n 32 --dependency=afterany:$job8_0 haddock3 "dpp-local-nc32_gl5-12.cfg" | awk '{print $NF}')
job8_2=$(sbatch --job-name="info.after.dpp-local-nc32_gl5-12.cfg" -w gl5 -n 1 --dependency=afterany:$job8_1 collect-info.after.sh | awk '{print $NF}')
job9_0=$(sbatch --job-name="info.before.daa-local-nc16_gl5-11.cfg" -w gl5 -n 1 --dependency=afterany:$job8_2 collect-info.before.sh | awk '{print $NF}')
job9_1=$(sbatch --job-name="daa-local-nc16_gl5-11.cfg" -w gl5 -n 16 --dependency=afterany:$job9_0 haddock3 "daa-local-nc16_gl5-11.cfg" | awk '{print $NF}')
job9_2=$(sbatch --job-name="info.after.daa-local-nc16_gl5-11.cfg" -w gl5 -n 1 --dependency=afterany:$job9_1 collect-info.after.sh | awk '{print $NF}')
job10_0=$(sbatch --job-name="info.before.dpp-local-nc8_gl5-11.cfg" -w gl5 -n 1 --dependency=afterany:$job9_2 collect-info.before.sh | awk '{print $NF}')
job10_1=$(sbatch --job-name="dpp-local-nc8_gl5-11.cfg" -w gl5 -n 8 --dependency=afterany:$job10_0 haddock3 "dpp-local-nc8_gl5-11.cfg" | awk '{print $NF}')
job10_2=$(sbatch --job-name="info.after.dpp-local-nc8_gl5-11.cfg" -w gl5 -n 1 --dependency=afterany:$job10_1 collect-info.after.sh | awk '{print $NF}')
job11_0=$(sbatch --job-name="info.before.dpp-local-nc32_gl5-14.cfg" -w gl5 -n 1 --dependency=afterany:$job10_2 collect-info.before.sh | awk '{print $NF}')
job11_1=$(sbatch --job-name="dpp-local-nc32_gl5-14.cfg" -w gl5 -n 32 --dependency=afterany:$job11_0 haddock3 "dpp-local-nc32_gl5-14.cfg" | awk '{print $NF}')
job11_2=$(sbatch --job-name="info.after.dpp-local-nc32_gl5-14.cfg" -w gl5 -n 1 --dependency=afterany:$job11_1 collect-info.after.sh | awk '{print $NF}')
job12_0=$(sbatch --job-name="info.before.daa-local-nc8_gl5-12.cfg" -w gl5 -n 1 --dependency=afterany:$job11_2 collect-info.before.sh | awk '{print $NF}')
job12_1=$(sbatch --job-name="daa-local-nc8_gl5-12.cfg" -w gl5 -n 8 --dependency=afterany:$job12_0 haddock3 "daa-local-nc8_gl5-12.cfg" | awk '{print $NF}')
job12_2=$(sbatch --job-name="info.after.daa-local-nc8_gl5-12.cfg" -w gl5 -n 1 --dependency=afterany:$job12_1 collect-info.after.sh | awk '{print $NF}')
job13_0=$(sbatch --job-name="info.before.dpp-local-nc2_gl5-18.cfg" -w gl5 -n 1 --dependency=afterany:$job12_2 collect-info.before.sh | awk '{print $NF}')
job13_1=$(sbatch --job-name="dpp-local-nc2_gl5-18.cfg" -w gl5 -n 2 --dependency=afterany:$job13_0 haddock3 "dpp-local-nc2_gl5-18.cfg" | awk '{print $NF}')
job13_2=$(sbatch --job-name="info.after.dpp-local-nc2_gl5-18.cfg" -w gl5 -n 1 --dependency=afterany:$job13_1 collect-info.after.sh | awk '{print $NF}')
job14_0=$(sbatch --job-name="info.before.dpp-local-nc2_gl5-14.cfg" -w gl5 -n 1 --dependency=afterany:$job13_2 collect-info.before.sh | awk '{print $NF}')
job14_1=$(sbatch --job-name="dpp-local-nc2_gl5-14.cfg" -w gl5 -n 2 --dependency=afterany:$job14_0 haddock3 "dpp-local-nc2_gl5-14.cfg" | awk '{print $NF}')
job14_2=$(sbatch --job-name="info.after.dpp-local-nc2_gl5-14.cfg" -w gl5 -n 1 --dependency=afterany:$job14_1 collect-info.after.sh | awk '{print $NF}')
job15_0=$(sbatch --job-name="info.before.daa-local-nc8_gl5-13.cfg" -w gl5 -n 1 --dependency=afterany:$job14_2 collect-info.before.sh | awk '{print $NF}')
job15_1=$(sbatch --job-name="daa-local-nc8_gl5-13.cfg" -w gl5 -n 8 --dependency=afterany:$job15_0 haddock3 "daa-local-nc8_gl5-13.cfg" | awk '{print $NF}')
job15_2=$(sbatch --job-name="info.after.daa-local-nc8_gl5-13.cfg" -w gl5 -n 1 --dependency=afterany:$job15_1 collect-info.after.sh | awk '{print $NF}')
job16_0=$(sbatch --job-name="info.before.dpp-local-nc2_gl5-17.cfg" -w gl5 -n 1 --dependency=afterany:$job15_2 collect-info.before.sh | awk '{print $NF}')
job16_1=$(sbatch --job-name="dpp-local-nc2_gl5-17.cfg" -w gl5 -n 2 --dependency=afterany:$job16_0 haddock3 "dpp-local-nc2_gl5-17.cfg" | awk '{print $NF}')
job16_2=$(sbatch --job-name="info.after.dpp-local-nc2_gl5-17.cfg" -w gl5 -n 1 --dependency=afterany:$job16_1 collect-info.after.sh | awk '{print $NF}')
job17_0=$(sbatch --job-name="info.before.daa-local-nc2_gl5-15.cfg" -w gl5 -n 1 --dependency=afterany:$job16_2 collect-info.before.sh | awk '{print $NF}')
job17_1=$(sbatch --job-name="daa-local-nc2_gl5-15.cfg" -w gl5 -n 2 --dependency=afterany:$job17_0 haddock3 "daa-local-nc2_gl5-15.cfg" | awk '{print $NF}')
job17_2=$(sbatch --job-name="info.after.daa-local-nc2_gl5-15.cfg" -w gl5 -n 1 --dependency=afterany:$job17_1 collect-info.after.sh | awk '{print $NF}')
job18_0=$(sbatch --job-name="info.before.dpp-local-nc16_gl5-12.cfg" -w gl5 -n 1 --dependency=afterany:$job17_2 collect-info.before.sh | awk '{print $NF}')
job18_1=$(sbatch --job-name="dpp-local-nc16_gl5-12.cfg" -w gl5 -n 16 --dependency=afterany:$job18_0 haddock3 "dpp-local-nc16_gl5-12.cfg" | awk '{print $NF}')
job18_2=$(sbatch --job-name="info.after.dpp-local-nc16_gl5-12.cfg" -w gl5 -n 1 --dependency=afterany:$job18_1 collect-info.after.sh | awk '{print $NF}')
job19_0=$(sbatch --job-name="info.before.daa-local-nc8_gl5-15.cfg" -w gl5 -n 1 --dependency=afterany:$job18_2 collect-info.before.sh | awk '{print $NF}')
job19_1=$(sbatch --job-name="daa-local-nc8_gl5-15.cfg" -w gl5 -n 8 --dependency=afterany:$job19_0 haddock3 "daa-local-nc8_gl5-15.cfg" | awk '{print $NF}')
job19_2=$(sbatch --job-name="info.after.daa-local-nc8_gl5-15.cfg" -w gl5 -n 1 --dependency=afterany:$job19_1 collect-info.after.sh | awk '{print $NF}')
job20_0=$(sbatch --job-name="info.before.daa-local-nc4_gl5-11.cfg" -w gl5 -n 1 --dependency=afterany:$job19_2 collect-info.before.sh | awk '{print $NF}')
job20_1=$(sbatch --job-name="daa-local-nc4_gl5-11.cfg" -w gl5 -n 4 --dependency=afterany:$job20_0 haddock3 "daa-local-nc4_gl5-11.cfg" | awk '{print $NF}')
job20_2=$(sbatch --job-name="info.after.daa-local-nc4_gl5-11.cfg" -w gl5 -n 1 --dependency=afterany:$job20_1 collect-info.after.sh | awk '{print $NF}')
job21_0=$(sbatch --job-name="info.before.daa-local-nc2_gl5-18.cfg" -w gl5 -n 1 --dependency=afterany:$job20_2 collect-info.before.sh | awk '{print $NF}')
job21_1=$(sbatch --job-name="daa-local-nc2_gl5-18.cfg" -w gl5 -n 2 --dependency=afterany:$job21_0 haddock3 "daa-local-nc2_gl5-18.cfg" | awk '{print $NF}')
job21_2=$(sbatch --job-name="info.after.daa-local-nc2_gl5-18.cfg" -w gl5 -n 1 --dependency=afterany:$job21_1 collect-info.after.sh | awk '{print $NF}')
job22_0=$(sbatch --job-name="info.before.daa-local-nc2_gl5-16.cfg" -w gl5 -n 1 --dependency=afterany:$job21_2 collect-info.before.sh | awk '{print $NF}')
job22_1=$(sbatch --job-name="daa-local-nc2_gl5-16.cfg" -w gl5 -n 2 --dependency=afterany:$job22_0 haddock3 "daa-local-nc2_gl5-16.cfg" | awk '{print $NF}')
job22_2=$(sbatch --job-name="info.after.daa-local-nc2_gl5-16.cfg" -w gl5 -n 1 --dependency=afterany:$job22_1 collect-info.after.sh | awk '{print $NF}')
job23_0=$(sbatch --job-name="info.before.dpp-local-nc16_gl5-11.cfg" -w gl5 -n 1 --dependency=afterany:$job22_2 collect-info.before.sh | awk '{print $NF}')
job23_1=$(sbatch --job-name="dpp-local-nc16_gl5-11.cfg" -w gl5 -n 16 --dependency=afterany:$job23_0 haddock3 "dpp-local-nc16_gl5-11.cfg" | awk '{print $NF}')
job23_2=$(sbatch --job-name="info.after.dpp-local-nc16_gl5-11.cfg" -w gl5 -n 1 --dependency=afterany:$job23_1 collect-info.after.sh | awk '{print $NF}')
job24_0=$(sbatch --job-name="info.before.daa-local-nc16_gl5-12.cfg" -w gl5 -n 1 --dependency=afterany:$job23_2 collect-info.before.sh | awk '{print $NF}')
job24_1=$(sbatch --job-name="daa-local-nc16_gl5-12.cfg" -w gl5 -n 16 --dependency=afterany:$job24_0 haddock3 "daa-local-nc16_gl5-12.cfg" | awk '{print $NF}')
job24_2=$(sbatch --job-name="info.after.daa-local-nc16_gl5-12.cfg" -w gl5 -n 1 --dependency=afterany:$job24_1 collect-info.after.sh | awk '{print $NF}')
job25_0=$(sbatch --job-name="info.before.daa-local-nc8_gl5-14.cfg" -w gl5 -n 1 --dependency=afterany:$job24_2 collect-info.before.sh | awk '{print $NF}')
job25_1=$(sbatch --job-name="daa-local-nc8_gl5-14.cfg" -w gl5 -n 8 --dependency=afterany:$job25_0 haddock3 "daa-local-nc8_gl5-14.cfg" | awk '{print $NF}')
job25_2=$(sbatch --job-name="info.after.daa-local-nc8_gl5-14.cfg" -w gl5 -n 1 --dependency=afterany:$job25_1 collect-info.after.sh | awk '{print $NF}')
job26_0=$(sbatch --job-name="info.before.daa-local-nc2_gl5-11.cfg" -w gl5 -n 1 --dependency=afterany:$job25_2 collect-info.before.sh | awk '{print $NF}')
job26_1=$(sbatch --job-name="daa-local-nc2_gl5-11.cfg" -w gl5 -n 2 --dependency=afterany:$job26_0 haddock3 "daa-local-nc2_gl5-11.cfg" | awk '{print $NF}')
job26_2=$(sbatch --job-name="info.after.daa-local-nc2_gl5-11.cfg" -w gl5 -n 1 --dependency=afterany:$job26_1 collect-info.after.sh | awk '{print $NF}')
job27_0=$(sbatch --job-name="info.before.dpp-local-nc4_gl5-11.cfg" -w gl5 -n 1 --dependency=afterany:$job26_2 collect-info.before.sh | awk '{print $NF}')
job27_1=$(sbatch --job-name="dpp-local-nc4_gl5-11.cfg" -w gl5 -n 4 --dependency=afterany:$job27_0 haddock3 "dpp-local-nc4_gl5-11.cfg" | awk '{print $NF}')
job27_2=$(sbatch --job-name="info.after.dpp-local-nc4_gl5-11.cfg" -w gl5 -n 1 --dependency=afterany:$job27_1 collect-info.after.sh | awk '{print $NF}')
job28_0=$(sbatch --job-name="info.before.dpp-local-nc4_gl5-12.cfg" -w gl5 -n 1 --dependency=afterany:$job27_2 collect-info.before.sh | awk '{print $NF}')
job28_1=$(sbatch --job-name="dpp-local-nc4_gl5-12.cfg" -w gl5 -n 4 --dependency=afterany:$job28_0 haddock3 "dpp-local-nc4_gl5-12.cfg" | awk '{print $NF}')
job28_2=$(sbatch --job-name="info.after.dpp-local-nc4_gl5-12.cfg" -w gl5 -n 1 --dependency=afterany:$job28_1 collect-info.after.sh | awk '{print $NF}')
job29_0=$(sbatch --job-name="info.before.dpp-local-nc2_gl5-19.cfg" -w gl5 -n 1 --dependency=afterany:$job28_2 collect-info.before.sh | awk '{print $NF}')
job29_1=$(sbatch --job-name="dpp-local-nc2_gl5-19.cfg" -w gl5 -n 2 --dependency=afterany:$job29_0 haddock3 "dpp-local-nc2_gl5-19.cfg" | awk '{print $NF}')
job29_2=$(sbatch --job-name="info.after.dpp-local-nc2_gl5-19.cfg" -w gl5 -n 1 --dependency=afterany:$job29_1 collect-info.after.sh | awk '{print $NF}')
job30_0=$(sbatch --job-name="info.before.dpp-local-nc2_gl5-16.cfg" -w gl5 -n 1 --dependency=afterany:$job29_2 collect-info.before.sh | awk '{print $NF}')
job30_1=$(sbatch --job-name="dpp-local-nc2_gl5-16.cfg" -w gl5 -n 2 --dependency=afterany:$job30_0 haddock3 "dpp-local-nc2_gl5-16.cfg" | awk '{print $NF}')
job30_2=$(sbatch --job-name="info.after.dpp-local-nc2_gl5-16.cfg" -w gl5 -n 1 --dependency=afterany:$job30_1 collect-info.after.sh | awk '{print $NF}')
job31_0=$(sbatch --job-name="info.before.dpp-local-nc8_gl5-12.cfg" -w gl5 -n 1 --dependency=afterany:$job30_2 collect-info.before.sh | awk '{print $NF}')
job31_1=$(sbatch --job-name="dpp-local-nc8_gl5-12.cfg" -w gl5 -n 8 --dependency=afterany:$job31_0 haddock3 "dpp-local-nc8_gl5-12.cfg" | awk '{print $NF}')
job31_2=$(sbatch --job-name="info.after.dpp-local-nc8_gl5-12.cfg" -w gl5 -n 1 --dependency=afterany:$job31_1 collect-info.after.sh | awk '{print $NF}')
job32_0=$(sbatch --job-name="info.before.dpp-local-nc32_gl5-13.cfg" -w gl5 -n 1 --dependency=afterany:$job31_2 collect-info.before.sh | awk '{print $NF}')
job32_1=$(sbatch --job-name="dpp-local-nc32_gl5-13.cfg" -w gl5 -n 32 --dependency=afterany:$job32_0 haddock3 "dpp-local-nc32_gl5-13.cfg" | awk '{print $NF}')
job32_2=$(sbatch --job-name="info.after.dpp-local-nc32_gl5-13.cfg" -w gl5 -n 1 --dependency=afterany:$job32_1 collect-info.after.sh | awk '{print $NF}')
job33_0=$(sbatch --job-name="info.before.dpp-local-nc2_gl5-13.cfg" -w gl5 -n 1 --dependency=afterany:$job32_2 collect-info.before.sh | awk '{print $NF}')
job33_1=$(sbatch --job-name="dpp-local-nc2_gl5-13.cfg" -w gl5 -n 2 --dependency=afterany:$job33_0 haddock3 "dpp-local-nc2_gl5-13.cfg" | awk '{print $NF}')
job33_2=$(sbatch --job-name="info.after.dpp-local-nc2_gl5-13.cfg" -w gl5 -n 1 --dependency=afterany:$job33_1 collect-info.after.sh | awk '{print $NF}')
job34_0=$(sbatch --job-name="info.before.daa-local-nc2_gl5-19.cfg" -w gl5 -n 1 --dependency=afterany:$job33_2 collect-info.before.sh | awk '{print $NF}')
job34_1=$(sbatch --job-name="daa-local-nc2_gl5-19.cfg" -w gl5 -n 2 --dependency=afterany:$job34_0 haddock3 "daa-local-nc2_gl5-19.cfg" | awk '{print $NF}')
job34_2=$(sbatch --job-name="info.after.daa-local-nc2_gl5-19.cfg" -w gl5 -n 1 --dependency=afterany:$job34_1 collect-info.after.sh | awk '{print $NF}')
job35_0=$(sbatch --job-name="info.before.dpp-local-nc2_gl5-11.cfg" -w gl5 -n 1 --dependency=afterany:$job34_2 collect-info.before.sh | awk '{print $NF}')
job35_1=$(sbatch --job-name="dpp-local-nc2_gl5-11.cfg" -w gl5 -n 2 --dependency=afterany:$job35_0 haddock3 "dpp-local-nc2_gl5-11.cfg" | awk '{print $NF}')
job35_2=$(sbatch --job-name="info.after.dpp-local-nc2_gl5-11.cfg" -w gl5 -n 1 --dependency=afterany:$job35_1 collect-info.after.sh | awk '{print $NF}')
job36_0=$(sbatch --job-name="info.before.dpp-local-nc2_gl5-12.cfg" -w gl5 -n 1 --dependency=afterany:$job35_2 collect-info.before.sh | awk '{print $NF}')
job36_1=$(sbatch --job-name="dpp-local-nc2_gl5-12.cfg" -w gl5 -n 2 --dependency=afterany:$job36_0 haddock3 "dpp-local-nc2_gl5-12.cfg" | awk '{print $NF}')
job36_2=$(sbatch --job-name="info.after.dpp-local-nc2_gl5-12.cfg" -w gl5 -n 1 --dependency=afterany:$job36_1 collect-info.after.sh | awk '{print $NF}')
job37_0=$(sbatch --job-name="info.before.daa-local-nc8_gl5-11.cfg" -w gl5 -n 1 --dependency=afterany:$job36_2 collect-info.before.sh | awk '{print $NF}')
job37_1=$(sbatch --job-name="daa-local-nc8_gl5-11.cfg" -w gl5 -n 8 --dependency=afterany:$job37_0 haddock3 "daa-local-nc8_gl5-11.cfg" | awk '{print $NF}')
job37_2=$(sbatch --job-name="info.after.daa-local-nc8_gl5-11.cfg" -w gl5 -n 1 --dependency=afterany:$job37_1 collect-info.after.sh | awk '{print $NF}')
job38_0=$(sbatch --job-name="info.before.daa-local-nc2_gl5-13.cfg" -w gl5 -n 1 --dependency=afterany:$job37_2 collect-info.before.sh | awk '{print $NF}')
job38_1=$(sbatch --job-name="daa-local-nc2_gl5-13.cfg" -w gl5 -n 2 --dependency=afterany:$job38_0 haddock3 "daa-local-nc2_gl5-13.cfg" | awk '{print $NF}')
job38_2=$(sbatch --job-name="info.after.daa-local-nc2_gl5-13.cfg" -w gl5 -n 1 --dependency=afterany:$job38_1 collect-info.after.sh | awk '{print $NF}')
job39_0=$(sbatch --job-name="info.before.dpp-local-nc4_gl5-13.cfg" -w gl5 -n 1 --dependency=afterany:$job38_2 collect-info.before.sh | awk '{print $NF}')
job39_1=$(sbatch --job-name="dpp-local-nc4_gl5-13.cfg" -w gl5 -n 4 --dependency=afterany:$job39_0 haddock3 "dpp-local-nc4_gl5-13.cfg" | awk '{print $NF}')
job39_2=$(sbatch --job-name="info.after.dpp-local-nc4_gl5-13.cfg" -w gl5 -n 1 --dependency=afterany:$job39_1 collect-info.after.sh | awk '{print $NF}')
job40_0=$(sbatch --job-name="info.before.dpp-local-nc32_gl5-11.cfg" -w gl5 -n 1 --dependency=afterany:$job39_2 collect-info.before.sh | awk '{print $NF}')
job40_1=$(sbatch --job-name="dpp-local-nc32_gl5-11.cfg" -w gl5 -n 32 --dependency=afterany:$job40_0 haddock3 "dpp-local-nc32_gl5-11.cfg" | awk '{print $NF}')
job40_2=$(sbatch --job-name="info.after.dpp-local-nc32_gl5-11.cfg" -w gl5 -n 1 --dependency=afterany:$job40_1 collect-info.after.sh | awk '{print $NF}')
cat > check-local-exp-gl5.sh << EOF
#!/bin/bash
echo $job1_1,$job2_1,$job3_1,$job4_1,$job5_1,$job6_1,$job7_1,$job8_1,$job9_1,$job10_1,$job11_1,$job12_1,$job13_1,$job14_1,$job15_1,$job16_1,$job17_1,$job18_1,$job19_1,$job20_1,$job21_1,$job22_1,$job23_1,$job24_1,$job25_1,$job26_1,$job27_1,$job28_1,$job29_1,$job30_1,$job31_1,$job32_1,$job33_1,$job34_1,$job35_1,$job36_1,$job37_1,$job38_1,$job39_1,$job40_1
sacct -o jobid,jobname%50,cluster,Node,state,start,end,ConsumedEnergy,AveRSS,AveDiskRead,AveDiskWrite,AveVMSize,elapsed,NCPUS     -j $job1_1,$job2_1,$job3_1,$job4_1,$job5_1,$job6_1,$job7_1,$job8_1,$job9_1,$job10_1,$job11_1,$job12_1,$job13_1,$job14_1,$job15_1,$job16_1,$job17_1,$job18_1,$job19_1,$job20_1,$job21_1,$job22_1,$job23_1,$job24_1,$job25_1,$job26_1,$job27_1,$job28_1,$job29_1,$job30_1,$job31_1,$job32_1,$job33_1,$job34_1,$job35_1,$job36_1,$job37_1,$job38_1,$job39_1,$job40_1     > local-exp-gl5-data.txt
cat local-exp-gl5-data.txt
EOF
